app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');




Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');

    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});



Route::group(['middleware' => ['auth'], 'prefix' => "admin/temp", 'as' => "admin.temp."], function () {
    Route::get('/', 'candidateController@index')->name('index');
    Route::delete('{id}/delete', 'candidateController@delete')->name('delete');
    Route::get('{id}/edit', 'candidateController@edit')->name('edit');
    Route::get('add', 'candidateController@add')->name('add');
    Route::post('save', 'candidateController@save')->name('save');

});

Route::auth();

resources/views/temp/base.blade.php
<?php 
	$i ="" ; $j = "";
 ?>
@extends('admin.master')
@section('plugins_css')
@stop

@section('plugins_js')

@stop

@section('page_js')
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/candidates.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
Candidates
@stop

@section('page_title')
Candidates
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/temp/edit_form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="name" class="form-control" value="{{$candidate->name}}">
                    <input type="hidden" name="id" id="hiddenField" value="{{$candidate->id}}" />
                                                  </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="email" class="form-control" value="{{$candidate->email}}" >
                </div>
                <div class="form-group">
                    <label>Mobile</label>
                    <input name="mobile" class="form-control" value="{{$candidate->phone}}" >
                </div>
                <div class="form-group">
                    <label>Phase</label>
                    <select name="user_phase" class="form-control" >
                    	<option value="testing" <?php if($candidate->user_phase == "testing"){?> selected="selected"<?php ;}?>>Testing</option>
                    	<option value="testEvaluation" <?php if($candidate->user_phase == "testEvaluation"){?> selected="selected"<?php ;}?>>Test Evaluation</option>
                    	<option value="phoneInterview" <?php if($candidate->user_phase == "phoneInterview"){?> selected="selected"<?php ;}?>>Phone Interview</option>
                    	<option value="pilotTest" <?php if($candidate->user_phase == "pilotTest"){?> selected="selected"<?php ;}?>>Pilot Test</option>
                    	<option value="passedAll" <?php if($candidate->user_phase == "passedAll"){?> selected="selected"<?php ;}?>>Passed All</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <select name="user_status" class="form-control" >
                    	<option value="Pending" <?php if($candidate->user_status == "Pending"){?> selected="selected"<?php ;}?>>Pending</option>
                    	<option value="Approved" <?php if($candidate->user_status == "Approved"){?> selected="selected"<?php ;}?>>Approved</option>
                    	<option value="Rejected" <?php if($candidate->user_status == "Rejected"){?> selected="selected"<?php ;}?>>Rejected</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Quiz grade</label>
                    <input name="quiz" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->quiz}}@endif" >
                </div>
                <div class="form-group">
                    <label>Fluency</label>
                    <input name="fluency" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->fluency}}@endif" >
                </div>
                <div class="form-group">
                    <label>Vocab</label>
                    <input name="vocab" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->vocab}}@endif" >
                </div>
                <div class="form-group">
                    <label>Grammar</label>
                    <input name="grammar" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->grammar}}@endif" >
                </div>
                <div class="form-group">
                    <label>Accent</label>
                    <input name="accent" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->accent}}@endif" >
                </div>
                <div class="form-group">
                    <label>Pilot test grade</label>
                    <input name="pilot" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->pilot}}@endif" >
                </div>
               
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all-edit" data-action="{{route('admin.candidates.saveEdit')}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>

resources/views/temp/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{route('admin.temp.save')}}" method="post" class="ajax_form">
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="name" class="form-control" data-validation="required" data-name="Name"  >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="text" data-validation="required,email" data-name="Email"  class="form-control" >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>mobile</label>
                    <input name="mobile" data-validation="required,number" data-name="Mobile" class="form-control" >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>password</label>
                    <input name="password" data-validation="required" data-name="password" type="password" class="form-control" >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>Retype field</label>
                    <input name="password2" data-validation="required,match.password" data-name="password" type="password" class="form-control" >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input name="date" data-validation="required" data-name="Date" type="text" class="form-control datePicker" >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>Date & Time</label>
                    <input name="dateTime" data-validation="required" data-name="Date & Time" type="text" class="form-control timepicker" >
                    <span class="error_message"></span>
                </div>
                <div class="form-group">
                    <label>Dropdown</label>
                    <select name="dropdown" data-validation="required" data-name="Dropdown" class="form-control">
                    	<option value="">Select Option</option>
                    	<option value="1">1</option>
                    </select>
                    <span class="error_message"></span>
                </div>
                
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="submit" class="btn btn-lg green"  >Save</button>
                </div>
            </div>
        </div>
        <input type="reset" class="hide resetForm" >
        </form>
        <!-- END FORM-->
    </div>
</div>
@include('quizzes.templates')

resources/views/temp/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Candidates
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.temp.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Title
                    </th>
                    <th valign="middle">Email</th>
                    <th valign="middle">Mobile</th>
                    <?php if($user_phase == "testEvaluation" || $user_phase == "phoneInterview"){?> <th valign="middle">Test Degree</th> <?php ;}?>
                    <?php if($user_phase == "pilotTest"){?><th valign="middle">Pilot</th><?php ;}?>
                   
                    <?php if($user_status == "Rejected" || $user_status == "all" ){?>
                    <th valign="middle">Phase &amp; Grades</th>
                    <?php ;}?>
                    
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($candidates as $candidate)
                <tr class="odd gradeX" id="data-row-{{$candidate->id}}" data-user_id = "{{$candidate->id}}">
                    <td valign="middle">
                        {{$candidate->name}}
                    </td>
                    <td valign="middle">{{$candidate->email}}</td>
                    <td valign="middle">{{$candidate->phone}}</td>
                    <?php if($candidate->user_phase == "testEvaluation" || $user_phase == "phoneInterview"){?><td valign="middle">{{$candidate->getGrades->quiz}}</td><?php ;}?>
                    <?php if($user_phase == "pilotTest"){?><td valign="middle"><?php if($candidate->pilot_ready == 1){?>Ready<?php ;}else{?>Not ready<?php ;}?></td><?php ;}?>
                    
                    <?php if($user_status == "Rejected" || $user_status == "all" ){?><td valign="middle">
                      <table width="100%" border="0" cellspacing="0" cellpadding="0" class="grades">
                        <tr>
                        <th align="center" scope="col">Phase</th>
                        <th align="center" scope="col">Status</th>
                          <th align="center" scope="col">Quiz</th>
                          <th align="center" scope="col">Fluency</th>
                          <th align="center" scope="col">Vocab</th>
                          <th align="center" scope="col">Grammar</th>
                          <th align="center" scope="col">Accent</th>
                          <th align="center" scope="col">Pilot</th>
                        </tr>
                        <tr>
                        <td align="center">{{$candidate->user_phase}}</td>
                        <td align="center">{{$candidate->user_status}}</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->quiz}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->fluency}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->vocab}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->grammar}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->accent}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->pilot}}@endif</td>
                        </tr>
                      </table></td><?php ;}?>
                    
                    <td valign="middle">
                    @if($candidate->user_status =="Pending" && $candidate->user_phase !="testing")
                    <a href="{{route('admin.temp.pass',['id'=>$candidate->id])}}" data-phase = "{{$candidate->user_phase}}" class="btn green candidate-change-status" ><i class="fa fa-check"></i> Pass</a>
                    <a href="#" data-action="{{route('admin.temp.delete',['id'=>$candidate->id])}}"  class="btn red delete_single" ><i class="fa fa-remove"></i> delete</a> 
                    
                    @endif
                    <?php if($user_status == "all" ){?>
                   	  <a href="{{route('admin.temp.edit',['id'=>$candidate->id])}}"  class="btn green pjax-link" ><i class="fa fa-edit"></i> edit</a> 	
                    <?php ;}?>
                    <a href="{{route('admin.temp.delete',['id'=>$candidate->id])}}"  class="btn blue delete_single" ><i class="fa fa-edit"></i> test details</a> 	
                    
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/temp/test_details.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Test Details
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.candidates.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">Question</th>
                    <th valign="middle">Student Degree</th>
                    <th valign="middle">Max degree</th>
                    <th valign="middle">Start time</th>
                    <th valign="middle">End time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($answers as $answer)
                <tr class="odd gradeX" id="data-row-{{$answer->id}}" data-user_id = "{{$answer->id}}">
                    <td valign="middle">
                    {{$answer->getQuestion->content}}
                        
                    </td>
                    <td valign="middle">{{$answer->degree}}</td>
                    <td valign="middle">{{$answer->getQuestion->weight}}</td>
                    <td valign="middle">{{$answer->getEntry->start_time}}</td>
                    <td valign="middle">{{$answer->getEntry->end_time}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/temp/view.blade.php
	<iframe width="100%" height="1000" src="{{$path}}" frameborder="0" scrolling="no"></iframe>